import profile_pic from "./profile_pic.jpg"
import menu_icon from "./menu_icon.png"
import plus_icon from "./plus_icon.png"
import message_icon from "./message_icon.png"
import question_icon from "./question_icon.png"
import history_icon from "./history_icon.png"
import setting_icon from "./setting_icon.png"
import send_icon from "./send_icon.png"
import mic_icon from "./mic_icon.png"
import gallery_icon from "./gallery_icon.png"
import user_icon from "./user_icon.png"
export const pics={user_icon,mic_icon,gallery_icon,send_icon,profile_pic,menu_icon,plus_icon,message_icon,question_icon,history_icon,setting_icon}